#!/bin/bash

JAVA=/home/astro/.jdks/openjdk-18.0.1.1/bin/java

JAVA_BIN=Tobi/bin/
JAVA_SRC=Tobi/src

CPP_INCLUDE=Kamui/include/
CPP_BIN=Kamui/bin
CPP_SRC=Kamui/src

#Building the java files to create the cpp header file
javac -d $JAVA_BIN -h $CPP_INCLUDE $JAVA_SRC/*/*.java

#Linking the cpp file and creating a .so
g++ $CPP_SRC/Tobi.cpp -I /usr/lib/jvm/java-17-openjdk-amd64/include/ -I /usr/lib/jvm/java-17-openjdk-amd64/include/linux -I $CPP_INCLUDE -shared -c -fPIC -Wall -o $CPP_BIN/Tobi.o
g++ -shared -fPIC -o $CPP_BIN/libnative.so $CPP_BIN/Tobi.o -lc

#Before the step, you need to rebuild the java class files with IntelliJ (this would create the "out" folder)
#The cpp .so path and the IntelliJ jar file to create the forms are specify
$JAVA -Djava.library.path=$CPP_BIN -javaagent:/home/astro/Downloads/idea-IC-221.5591.52/lib/idea_rt.jar=44891:/home/astro/Downloads/idea-IC-221.5591.52/bin -Dfile.encoding=UTF-8 -cp /mnt/hgfs/Tobi/Tobi-v2/Tobi/src/out/production/Tobi Tobi.Tobi