/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Tobi_Tobi */

#ifndef _Included_Tobi_Tobi
#define _Included_Tobi_Tobi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Tobi_Tobi
 * Method:    getPkt
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Tobi_Tobi_getPkt
  (JNIEnv *, jobject);

/*
 * Class:     Tobi_Tobi
 * Method:    sendPkt
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Tobi_Tobi_sendPkt
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Tobi_Tobi
 * Method:    kamui
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Tobi_Tobi_kamui
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
